plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.144'
}

version = '1.0.0'
group = 'com.kalil.latclima'
base { archivesName = 'latclima' }

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenLocal()
}

neoForge {
    version = project.neo_version
}
